apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: pytorch/pytorch
    resources:
      limits:
        memory: 1Gi
        cpu: 2
      requests:
        memory: 512Mi
        cpu: 1
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
