apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  template:
    spec:
      containers:
      - name: demo
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
        command:
        - sh
        - -c
        - "cd /persistentvol && python decisiontree.py"
        volumeMounts:
        - name: persistentvol
          mountPath: /persistentvol
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            memory: 8Gi
            cpu: "2"
      volumes:
      - name: persistentvol
        persistentVolumeClaim:
          claimName: jonathan-nuscenes
      restartPolicy: Never
  backoffLimit: 5
