apiVersion: v1
kind: Pod
metadata:
  name: test-windows
spec:
  containers:
  - name: mypod
    image: dockurr/windows
    resources:
      limits:
        memory: 10Gi
        cpu: 4
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
